#runtime: custom
#env: flex

runtime: python38

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index.html

  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico

  - url: /(.*\.js)
    mime_type: text/javascript
    static_files: static/\1
    upload: static/(.*\.js)